CREATE SEQUENCE IF NOT EXISTS arquivos_impl_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
CACHE 1;

CREATE TABLE IF NOT EXISTS ARQUIVOS_IMPLANTACAO_BD(
	id INT PRIMARY KEY DEFAULT nextval('arquivos_impl_seq'::regclass),
	nome_arquivo CHARACTER VARYING(50) NOT NULL
);